#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


branchname=$(git rev-parse --abbrev-ref HEAD)

if [[ ! $branchname == "HEAD" && ! $branchname == main  ]]; then
  tools/enforce-gitmoji.sh "$(cat tools/gitmoji.regexp)" $1
fi
